### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ericnost**
Adds table of notebooks with permalinks. Should linkify the Notebook itself, but this is a start

### CODE REVIEW

**Comment by ericnost** [comment]
can't request reviewers because I don't have access, but: @Frijol

**Comment by ericnost** [comment]
Fixes edgi-govdata-archiving/Environmental-Enforcement-Watch/issues/15

**Comment by Frijol** [comment]
whoops updated permissions, now this repo is included

**Review by Frijol — APPROVED** [review]
descriptions to follow, I take it?

**Comment by ericnost** [comment]
Descriptions forthcoming yes...I still don't have write access. Can you merge?

**Comment by ericnost** [comment]
@Frijol Could you merge? Will help with edgi-govdata-archiving/EEW_Planning/issues/124

**Pull request merged**
